# Copyright (c) 2025 Ember
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: Docker Buildrunner

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
####################################################################
# Linux – Docker Build
####################################################################
  Linux_Ubuntu_ARM64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Restore Docker Buildx Cache
        uses: actions/cache@v3
        with:
          path: /tmp/docker-cache
          key: docker-cache-${{ runner.os }}-${{ hashFiles('Dockerfile') }}
          restore-keys: docker-cache-${{ runner.os }}

      - name: Build the Docker image with caching
        run: |
          docker buildx create --use --name mybuilder || docker buildx use mybuilder
          docker buildx build --file Dockerfile \
            --cache-from=type=local,src=/tmp/docker-cache \
            --cache-to=type=local,dest=/tmp/docker-cache,mode=max \
            .
