# Copyright (c) 2025 Ember
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: Windows (MSVC) CI
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  # Windows – Cached Debug Build
  x86_64_debug:
    runs-on: windows-2025
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Cache Dependencies and Homebrew
        uses: actions/cache@v3
        with:
          path: |
            C:\Users\runneradmin\.conan2
            C:\flatbuffers
            C:\mysql-connector-c++\
            dependencies
          key: win-deps
          restore-keys: win-deps

      - name: Cache Build Folder
        uses: actions/cache@v3
        with:
          path: build
          key: win-build-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: win-build-

      - name: Run Windows Build Script
        shell: pwsh
        run: .\docs\scripts\build_windows.ps1

  # Windows ARM – Cached Debug Build
  ARM64_debug:
    runs-on: windows-11-arm
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Cache Dependencies and Homebrew
        uses: actions/cache@v3
        with:
          path: |
            C:\Users\runneradmin\.conan2
            C:\flatbuffers
            C:\mysql-connector-c++\
            dependencies
          key: win_arm-deps
          restore-keys: win_arm-deps

      - name: Cache Build Folder
        uses: actions/cache@v3
        with:
          path: build
          key: win_arm-build-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: win_arm-build-

      - name: Run Windows Build Script
        shell: pwsh
        run: .\docs\scripts\build_windows.ps1
